"""Initial migration

Revision ID: e5eb9bc15d5e
Revises: 
Create Date: 2024-09-20 20:55:26.215526

"""
from alembic import op
import sqlalchemy as sa

import models

# revision identifiers, used by Alembic.
revision = 'e5eb9bc15d5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', models.EncryptedType(), nullable=False),
    sa.Column('first_name', models.EncryptedType(), nullable=False),
    sa.Column('last_name', models.EncryptedType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
